branch:
  development:
    - artifact_name: development
      tenant: BofA-QA
      target: SOS-policy_groups
      enforce: true
  staging:
    - artifact_name: staging_bofa-qa
      tenant: BofA-QA
      target: BofA
      enforce: true
    - artifact_name: staging_poc
      tenant: BofA
      target: POC
      enforce: true
    - artifact_name: staging_pok
      tenant: BofA
      target: staging_pok
      enforce: true